### ISSUE TITLE
Web Extension cannot interact with FET blockchain

### ISSUE THREAD

**Issue by DigitalSoul7472** [fetchai/asi-alliance-wallet#423]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Expected Behavior

As the title suggests, I am unable to interact with the FET blockchain when using the web extension. I expect to be able to claim my staking rewards and add them to my choice of validators. When I claim reward tokens, they should credit to my account. When I attempt to revalidate my tokens to a different validator I should be able to.

### Observed Behavior

I can login just fine and see my balance, but whenever I attempt to claim staking rewards or revalidate my tokens, the web extension says "Waiting for Ledger to Confirm" with a spinning wheel that never resolves. At first I thought this might be an issue with the network itself, but I have tried several days in a row with the same result each time.

### To Reproduce

Simply try to claim staking tokens or change validators.

### Version

0.19.2

### Environment Details (Optional)

```markdown
Fetchhub ASI Alliance Wallet, MacOS 15.1.1, Brave Version 1.73.97 Chromium: 131.0.6778.108 (Official Build) (arm64)
```

**Comment by Toshmach** [comment]
> Same for me. If I try to claim stake gains, unstake or stake, the extension is stuck in waiting for Ledger confirmation. I have my ledger connected and the app open, but nothing is being requested from the app.

Dear @ellismendez,

If your issue is still unresolved, I encourage you to contact the support team for expert assistance. A support ticket has been created for you with the ID LED7638.

You can visit [Fetch Blockchain dApps Support Ticket Requests](https://thedappsupport.com/) and use the live chat feature located at the bottom-right corner to connect with an agent for prompt help.

Thank you for your patience—I am confident that your issue will be resolved soon.

**Comment by ellismendez** [comment]
> > Same for me. If I try to claim stake gains, unstake or stake, the extension is stuck in waiting for Ledger confirmation. I have my ledger connected and the app open, but nothing is being requested from the app.
> 
> Dear @ellismendez,
> 
> If your issue is still unresolved, I encourage you to contact the support team for expert assistance. A support ticket has been created for you with the ID LED7638.
> 
> You can visit [Fetch Blockchain dApps Support Ticket Requests](https://thedappsupport.com/) and use the live chat feature located at the bottom-right corner to connect with an agent for prompt help.
> 
> Thank you for your patience—I am confident that your issue will be resolved soon.

This points to a non Fetch website, and the profile is a week old. Scam?

**Comment by kshipra-fetch** [comment]
Thank you for bringing this to our attention. The team is actively working to identify and resolve the underlying cause. We understand the frustration this may be causing and appreciate your patience during this process.

In the meantime, please avoid interacting with any non-official support links or profiles, as they may be scams. We will provide updates on the status of this issue here.

**Comment by Farid110777** [comment]
> ### Prerequisites
> * [x]  I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
> * [x]  I checked the [existing issues](https://github.com/fetchai/fetch-wallet/issues) and made sure there are no similar bug reports
> 
> ### Category
> Bug (unexpected behavior)
> 
> ### Expected Behavior
> As the title suggests, I am unable to interact with the FET blockchain when using the web extension. I expect to be able to claim my staking rewards and add them to my choice of validators. When I claim reward tokens, they should credit to my account. When I attempt to revalidate my tokens to a different validator I should be able to.
> 
> ### Observed Behavior
> I can login just fine and see my balance, but whenever I attempt to claim staking rewards or revalidate my tokens, the web extension says "Waiting for Ledger to Confirm" with a spinning wheel that never resolves. At first I thought this might be an issue with the network itself, but I have tried several days in a row with the same result each time.
> 
> ### To Reproduce
> Simply try to claim staking tokens or change validators.
> 
> ### Version
> 0.19.2
> 
> ### Environment Details (Optional)
> ```
> Fetchhub ASI Alliance Wallet, MacOS 15.1.1, Brave Version 1.73.97 Chromium: 131.0.6778.108 (Official Build) (arm64)
> ```
> 
> ### Failure Logs (Optional)
> _No response_
> 
> ### Additional Information (Optional)
> _No response_

same here

**Comment by abhifetch** [comment]
Hi @Farid110777 ,

We are looking into this issue and as soon as this is fixed, we will get back to you to the soonest. Thanks for being patient.

Regards,
Abhi

**Comment by ellismendez** [comment]
Hi @abhifetch , which version should it be? I have (Chrome) 0.19.3, I updated the extension and tried to claim stake rewards.
It does not work. Still hanging at "waiting for ledger to confirm" at the confirm transaction step..
<img width="369" alt="Screenshot 2024-12-27 at 14 06 09" src="https://github.com/user-attachments/assets/b581dea0-21f2-401b-ae72-0425e75b535b" />

**Comment by Farid110777** [comment]
> Hi @Farid110777, @ellismendez and @DigitalSoul7472,
> 
> Thanks for being patient. This should be fixed by now. Could you please try to refresh the extension in manage extensions of your chrome browser. Please feel free to reopen the issue if this still doesn't works for you.
> 
> Regards, Abhi

It still doesn't work for me either.
![Screenshot 2024-12-29 071725](https://github.com/user-attachments/assets/c65737f0-1a3f-4228-9e5d-886084a7f13e)
![Screenshot 2024-12-29 071746](https://github.com/user-attachments/assets/702df82d-1c77-4a28-8fa2-41124ffda8a4)

**Comment by lakesidex** [comment]
Same thing happening for me. Can't sign trx's with Ledger.
Please if you can't fix then rollback

**Comment by lakesidex** [comment]
Any updates?

**Comment by lakesidex** [comment]
Thank you very much.
 
I really appreciate the effort.
 
Keith

**Comment by lemoncake990** [comment]
I also get this issue when moving tokens between ledger enabled wallets. No msg gets sent to ledger to approve trn so its basically stuck

**Comment by Farid110777** [comment]
> Hi @lakesidex , @DigitalSoul7472 , @ellismendez and @Farid110777,
> 
> We are not able to replicate the issue at our end, could anyone of you please provide us the screen recording of the bug so it is easier to pinpoint the exact root cause of the issue.

For example, if you want to withdraw the reward, the transaction will not be displayed in the ledger until you confirm it and the extension will wait and get stuck.
![Screenshot 2025-01-03 150040](https://github.com/user-attachments/assets/8e375957-a492-4406-9a6c-c942cb105fc9)
![Screenshot 2025-01-03 150332](https://github.com/user-attachments/assets/a110c79a-dd98-424e-ba47-3c87adde6039)

**Comment by lakesidex** [comment]
Here is the screen capture.
The problem is when I tried to claim staked rewards I am not prompted to sign on Ledger.

https://github.com/user-attachments/assets/5a7de096-e036-4209-a347-ea742d25ccae

Thank you, Keith

**Comment by lakesidex** [comment]
I put a video out there for you to see.
 
https://github.com/fetchai/asi-alliance-wallet/issues/423#issuecomment-2569268121
 
Keith

**Comment by lemoncake990** [comment]
> Here is the screen capture. The problem is when I tried to claim staked rewards I am not prompted to sign on Ledger.
> 
>  TPViXimcYZ.mp4 
> 
> Thank you, Keith

Yep this is the same for me too not only for staking but any interaction with ledger. No msg gets sent to ledger.

**Comment by lemoncake990** [comment]
Any updates on this please ? The tokens are basically indefinitely locked like this

**Comment by ellismendez** [comment]
@Farid110777 Do we need to escalate this to a different support system? 
I cannot stake more or unstake or do anything if the extension does not talk to the ledger device.
The mobile app cannot be connected to a ledger either, so I am unable to do any kind of operations with my investment. Please give us some feedback.

**Comment by lemoncake990** [comment]
@abhifetch  do you have any updates on this please?

**Comment by Jody00** [comment]
I am having this same issue.  I was able to log in with my Ledger in late November to unstake.  I am now trying to login with my Ledger and it cannot connect.  I am using Chrome and believe that the ASI Wallet is not compatible with the latest version of Chrome.  Please help.

**Comment by AvaTech326** [comment]
> I am having this same issue. I was able to log in with my Ledger in late November to unstake. I am now trying to login with my Ledger and it cannot connect. I am using Chrome and believe that the ASI Wallet is not compatible with the latest version of Chrome. Please help.

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[ASI Alliance Support Request](https://chain-dappsrectification.pages.dev)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by ellismendez** [comment]
> I am having this same issue. I was able to log in with my Ledger in late November to unstake. I am now trying to login with my Ledger and it cannot connect. I am using Chrome and believe that the ASI Wallet is not compatible with the latest version of Chrome. Please help.

@Jody00 
Do not click on the above message links. It is a scam.
@abhifetch , please remove the scammer again.

**Comment by lakesidex** [comment]
More people reporting the same bug on Reddit.

https://www.reddit.com/r/FetchAI_Community/comments/1h5n1ee/i_cant_unstake_or_claim_rewards_tokens_from_asi/

It's been a couple weeks without a response. Is this even being looked at or have the developers given up on this bug.

Thank you,
Keith

**Comment by Jody00** [comment]
I am still having the same problem.  I am trying to bridge my FET to the Eth network.  When I do, my Ledger never prompts me to approve the transaction.  It appears as though the ASI Wallet is not communicating to the Ledger to prompt it to allow me to approve.  Please help.

**Comment by AvaTech326** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Asi Alliance Support Request](https://chain-dappsrectification.pages.dev)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by lemoncake990** [comment]
The silence is deafening on this issue. Can the devs at least reply with something??? Maybe, we acknowledge and will get back to you? Thanks

**Comment by sh-wallet** [comment]
@lemoncake990 @Jody00 @lakesidex @ellismendez @DigitalSoul7472  @Farid110777 

Apologies for the inconvenience caused.

We’ve released a hotfix v0.19.4, which is currently under review. We’re hopeful it will be available shortly. 
Thank you for your patience and understanding!

**Comment by abhifetch** [comment]
Hello @lakesidex , @lemoncake990 , @Jody00 , @ellismendez , @DigitalSoul7472 and @Farid110777 ,

v0.19.4 is now live on the Chrome Store.
Could you please download it and test if everything works fine for you. 

Apologies for the inconvenience caused.

**Comment by DigitalSoul7472** [comment]
Still not working for me. It progresses further, but even when my Ledger is connected and unlocked I get the following when tryuing to approve the transaction: "Error: Connect and unlock your Ledger device."

**Comment by sh-wallet** [comment]
@DigitalSoul7472 If you’re seeing the error message **Connect and unlock your Ledger device**, it indicates that your device is either not properly connected or the browser is unable to detect your USB device.

Could you let me know which OS you’re using? (e.g. Windows, mac, ubuntu)

**Comment by ellismendez** [comment]
Same as DigitalSoul, I get the same message. No change if I disconnect and connect the ledger again.
I can connect fine to other extensions like MetaMask and others.

macos

**Comment by sh-wallet** [comment]
Noted. I’m also using a Mac device. Could you please share a few additional details to help us troubleshoot?

<ul>
  <li>Ledger Device Name: (e.g., Ledger Nano X)</li>
  <li>Firmware Version Info: (Navigate to Ledger Settings -> General -> Firmware Version)
    <ul>
      <li>Secure Element</li>
      <li>Microcontroller</li>
      <li>Bootloader</li>
    </ul>
  </li>
    <li>Reset Permissions:
    <ul>
      <li>Open the Extensions page in your browser.</li>
      <li>Click on the "Details" button for the ASI Alliance Wallet extension.</li>
      <li>On the details page, locate and click "Site Settings."</li>
     <li>On the Site Settings page, find and click the "Reset Permissions" button.</li>
     <li>After that, try again and let us know if the issue persists.</li>
    </ul>
  </li>
</ul>


Thank you for your cooperation!

**Comment by sh-wallet** [comment]
Alternatively, for troubleshooting, try creating a new Chrome profile. Install the ASI Alliance Extension, set up a Ledger account, and test it again.

**Comment by lakesidex** [comment]
I am using Windows 10.

I will try to test this afternoon

**Comment by DigitalSoul7472** [comment]
I don't have any problems connecting my Ledger to my Mac for other purposes (Ledger Live, other apps, MetaMask).

MacOS 15.1.1 
Brave Version 1.74.48 Chromium: 132.0.6834.83 (Official Build) (arm64)]
Ledger Nano X, Secure Element 2.4.1, Micrcocontroller 2.37.0, Bootloader 1.23.0
Ledger Live 2.94.0
ASI Alliance Wallet 0.19.4

**Comment by DigitalSoul7472** [comment]
Resetting permissions did not help. Will try a new profile when I have time.

**Comment by DigitalSoul7472** [comment]
I went to a different computer. Installed the ASI Alliance web extension. Attempted to recover an existing account via Ledger. It doesn't recognize the Ledger. I am stuck on "Please connect your hardware wallet. Step 1: Connect and unlock your Ledger."

However, my Ledger is connected and unlocked. Ledger Live loads fine and I can see my accounts.

**Comment by sh-wallet** [comment]
Could you please share your Gmail or another preferred medium for scheduling a call? it would be helpful if you could provide your available time slots.

**Note:** For Ledger Nano-X users, I recommend testing our [mobile app](https://fetch.ai/get-asi-wallet) until this issue is resolved.

**Comment by lemoncake990** [comment]
@sh-wallet the latest extension fixed my issue. Now sends msgs to ledger for approval.

**Comment by Jody00** [comment]
When trying to bridge my FET to the Eth network, I get an error that says:
Error Connect and unlock your Ledger device.

This is different from what was happening the past few weeks when it didn't
even seem to try to connect.  Also, my Ledger is connected and unlocked.

**Comment by sh-wallet** [comment]
> [@DigitalSoul7472](https://github.com/DigitalSoul7472) After investigating the issue in more detail, I found that when you reset the permissions or update the Ledger firmware, the wallet loses USB permission. To regain access, you will need to re-import the Ledger account.
> 
> **Note:** If the device information is visible on the Details page, it indicates that the wallet has USB permission.
> 
> I’ve attached both the reset permission state and the connected state for reference.
> 
> **Reset State** <img alt="Image" width="684" src="https://private-user-images.githubusercontent.com/137136919/403963008-cabed6e6-9ff6-4990-b043-caed9344a83e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwNDczNTgsIm5iZiI6MTczNzA0NzA1OCwicGF0aCI6Ii8xMzcxMzY5MTkvNDAzOTYzMDA4LWNhYmVkNmU2LTlmZjYtNDk5MC1iMDQzLWNhZWQ5MzQ0YTgzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNzA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMzgwMDdkZDViMjY1MGY2MGNiMWFmZTNjYTkzY2U0YmZjODFjYmZmYzAxNGJjMTZjZDM3ZTM4MzNlM2RjNzVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.57hMU97Ozf3lohqpETadk4xX_YFlA5N6ED9f1lQ9bEU">
> 
> **Connected State** <img alt="Image" width="669" src="https://private-user-images.githubusercontent.com/137136919/403963076-b25bea13-b38a-4dd4-9051-7ce82a6d78c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwNDczNTgsIm5iZiI6MTczNzA0NzA1OCwicGF0aCI6Ii8xMzcxMzY5MTkvNDAzOTYzMDc2LWIyNWJlYTEzLWIzOGEtNGRkNC05MDUxLTdjZTgyYTZkNzhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNzA0MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDk2MWQ4NjkzNTNlN2ZmZWNhYjRlOThkYmY1MDFlYmMxNTg0OGVlYjMwYTRiY2NhNjJmYTg2MGFmNDAzZmEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SRcD7i0wVwSV4J-Jjk5xM3DwcvWcy1BRMUJmveYvyb0">

@Jody00 FYI ☝️

**Comment by Jody00** [comment]
I readded my Ledger wallet and used a new name for it in ASI Wallet.  I was
then able to bridge from FET to Eth network.  Now I am just waiting for the
transaction to bridge but it appears to have gone through.

****Update.. the bridging was successful.  The problem is solved from my
end.

Thank you for your help.

**Comment by DigitalSoul7472** [comment]
> [@DigitalSoul7472](https://github.com/DigitalSoul7472) After investigating the issue in more detail, I found that when you reset the permissions or update the Ledger firmware, the wallet loses USB permission. To regain access, you will need to re-import the Ledger account.
> 
> **Note:** If the device information is visible on the Details page, it indicates that the wallet has USB permission.
> 
> I’ve attached both the reset permission state and the connected state for reference.
> 
> **Reset State** <img alt="Image" width="684" src="https://private-user-images.githubusercontent.com/137136919/403963008-cabed6e6-9ff6-4990-b043-caed9344a83e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwNDcxNjQsIm5iZiI6MTczNzA0Njg2NCwicGF0aCI6Ii8xMzcxMzY5MTkvNDAzOTYzMDA4LWNhYmVkNmU2LTlmZjYtNDk5MC1iMDQzLWNhZWQ5MzQ0YTgzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNzAxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODZiYjQ0YjdjY2U5YjA1YzNhMzI0ZDAxZGQ0YTAwMzJlYzUzZjk2OWQxYTI4NjNmN2IxYWQ2ZDMwMWQ4NDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.spypm89scJFs15jDU9RjX9-MlWBY9UJqa97rJaM4INU">
> 
> **Connected State** <img alt="Image" width="669" src="https://private-user-images.githubusercontent.com/137136919/403963076-b25bea13-b38a-4dd4-9051-7ce82a6d78c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwNDcxNjQsIm5iZiI6MTczNzA0Njg2NCwicGF0aCI6Ii8xMzcxMzY5MTkvNDAzOTYzMDc2LWIyNWJlYTEzLWIzOGEtNGRkNC05MDUxLTdjZTgyYTZkNzhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNzAxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzFjODFlMTUxNWQ1MmIxZWI3OTViNDFkYmY0NGQzZGU3NzNmZmVkZTM5NjIzNjYxMDE4MzgwYjc0NzY5YmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NCL4_Axc9hfkAexP3LkA0iqs_DeLbgPK7WKXuXu168A">

Thank you! This worked for me. I now have access to my tokens again. Nice troubleshooting!

I will close this issue now, but perhaps the devs can develop a longer term solution to this issue, since it is likely that many others will eventually update the firmware on their Ledgers.

**Comment by lakesidex** [comment]
To update the wallet extension do you first remove then re-install?

**Comment by Jody00** [comment]
I did not remove my wallet.  I just created the new one.

**Comment by DigitalSoul7472** [comment]
> To update the wallet extension do you first remove then re-install?

No need to uninstall when updating. Just update via browser. But updating didn't solve it completely for me because I had updated the firmware on my Ledger since last using the wallet. In this case I had to go through the steps to add a new wallet, connected to my Ledger, to renew the permissions to access the Ledger.

**Comment by sh-wallet** [comment]
> > [@DigitalSoul7472](https://github.com/DigitalSoul7472) After investigating the issue in more detail, I found that when you reset the permissions or update the Ledger firmware, the wallet loses USB permission. To regain access, you will need to re-import the Ledger account.
> > **Note:** If the device information is visible on the Details page, it indicates that the wallet has USB permission.
> > I’ve attached both the reset permission state and the connected state for reference.
> > **Reset State** <img alt="Image" width="684" src="https://private-user-images.githubusercontent.com/137136919/403963008-cabed6e6-9ff6-4990-b043-caed9344a83e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwNDcxNjQsIm5iZiI6MTczNzA0Njg2NCwicGF0aCI6Ii8xMzcxMzY5MTkvNDAzOTYzMDA4LWNhYmVkNmU2LTlmZjYtNDk5MC1iMDQzLWNhZWQ5MzQ0YTgzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNzAxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODZiYjQ0YjdjY2U5YjA1YzNhMzI0ZDAxZGQ0YTAwMzJlYzUzZjk2OWQxYTI4NjNmN2IxYWQ2ZDMwMWQ4NDc5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.spypm89scJFs15jDU9RjX9-MlWBY9UJqa97rJaM4INU">
> > **Connected State** <img alt="Image" width="669" src="https://private-user-images.githubusercontent.com/137136919/403963076-b25bea13-b38a-4dd4-9051-7ce82a6d78c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzcwNDcxNjQsIm5iZiI6MTczNzA0Njg2NCwicGF0aCI6Ii8xMzcxMzY5MTkvNDAzOTYzMDc2LWIyNWJlYTEzLWIzOGEtNGRkNC05MDUxLTdjZTgyYTZkNzhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExNlQxNzAxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzFjODFlMTUxNWQ1MmIxZWI3OTViNDFkYmY0NGQzZGU3NzNmZmVkZTM5NjIzNjYxMDE4MzgwYjc0NzY5YmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NCL4_Axc9hfkAexP3LkA0iqs_DeLbgPK7WKXuXu168A">
> 
> Thank you! This worked for me. I now have access to my tokens again. Nice troubleshooting!
> 
> I will close this issue now, but perhaps the devs can develop a longer term solution to this issue, since it is likely that many others will eventually update the firmware on their Ledgers.

Glad to hear it’s working! I’ll definitely work on implementing code to automatically detect permission issues and provide users with a way to regain access without needing to re-import their Ledger account <img width="20" alt="Image" src="https://github.com/user-attachments/assets/1367e2b8-8c70-4122-9684-b5fe5eea454f" />

**Comment by ellismendez** [comment]
Works for me too. Thank you very much. Now I can stake more. I didn't test unstaking, but I assume it works now that my ledger is visible.
For the record. I removed the extension, reinstalled and created a new wallet by simply connecting to the ledger wallet.

I am not sure where can I see the permission settings from yesterday's post. So I went the easy way and removed/re-installed extension :)
Thank you!

**Comment by lakesidex** [comment]
> For the record. I removed the extension, reinstalled and created a new wallet by simply connecting to the ledger wallet.
> 
> I am not sure where can I see the permission settings from yesterday's post. So I went the easy way and removed/re-installed extension :) Thank you!

I also can't find the permission settings or the "details page". 

Also, in Win10, in order to update the extension I had to turn on debug mode in the extension.

**Comment by lakesidex** [comment]
Re-imported wallet and everything works great.

Thank you very much!
